<?php

namespace Tracker\Model;
use League\OAuth2\Server\Entities\AuthCodeEntityInterface;
use League\OAuth2\Server\Repositories\AuthCodeRepositoryInterface;

/**
 * OA2AuthCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OA2AuthCodeRepository extends Base\OA2AuthCodeRepository implements AuthCodeRepositoryInterface
{
	public function getNewAuthCode()
	{
		return new OA2AuthCode();
	}

	public function persistNewAuthCode(AuthCodeEntityInterface $authCodeEntity)
	{
		/* @var OA2AuthCode $authCodeEntity */
		$authCodeEntity->save();
	}

	public function revokeAuthCode($codeId)
	{
		$authCode = $this->find($codeId);
		$authCode->setIsRevoked(true);
		$authCode->save();

		return $this;
	}

	public function isAuthCodeRevoked($codeId)
	{
		$authCode = $this->find($codeId);

		return $authCode->getIsRevoked();
	}
}
