<?php

namespace Tracker\Model;
use League\OAuth2\Server\Repositories\ClientRepositoryInterface;

/**
 * OA2ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OA2ClientRepository extends Base\OA2ClientRepository implements ClientRepositoryInterface
{
	public function getClientEntity($clientIdentifier, $grantType, $clientSecret = null, $mustValidateSecret = true)
	{
		return $this->findOneBy(['identifier' => $clientIdentifier]);
	}
}
