<?php

namespace Tracker\Model\Base;

/**
 * OA2AuthCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OA2AuthCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
