<?php

namespace Tracker\Model\Base;

/**
 * OA2RefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OA2RefreshTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
